# Generated by Django 5.2.8 on 2025-11-17 23:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Chart of accounts code', max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_as_of_date', models.DateField()),
                ('debit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='ledger.account')),
            ],
            options={
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entry_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reference_type', models.CharField(help_text='External system identifier: order, payment, subscription, refund, manual', max_length=50)),
                ('reference_id', models.CharField(help_text="External system's ID (string, no FK constraint for flexibility)", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-entry_number'],
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='ledger_jour_referen_351d6b_idx'), models.Index(fields=['date'], name='ledger_jour_date_d1775e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='ledger.journalentry')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['journal_entry', 'id'],
                'indexes': [models.Index(fields=['account', 'journal_entry'], name='ledger_ledg_account_b2bbec_idx')],
            },
        ),
    ]
