# Generated by Django 5.2.8 on 2025-11-17 23:30

from django.db import migrations
from decimal import Decimal


def create_chart_of_accounts(apps, schema_editor):
    Account = apps.get_model('ledger', 'Account')
    
    # Assets
    Account.objects.get_or_create(
        account_number='1000',
        defaults={
            'account_name': 'Cash',
            'account_type': 'Asset',
            'normal_balance': 'Debit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='1100',
        defaults={
            'account_name': 'Bank Account',
            'account_type': 'Asset',
            'normal_balance': 'Debit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='1200',
        defaults={
            'account_name': 'Accounts Receivable',
            'account_type': 'Asset',
            'normal_balance': 'Debit',
            'is_active': True
        }
    )
    
    # Liabilities
    Account.objects.get_or_create(
        account_number='2000',
        defaults={
            'account_name': 'Accounts Payable',
            'account_type': 'Liability',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='2100',
        defaults={
            'account_name': 'Vendor Payables',
            'account_type': 'Liability',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='2200',
        defaults={
            'account_name': 'Platform Fee Payable',
            'account_type': 'Liability',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    # Equity
    Account.objects.get_or_create(
        account_number='3000',
        defaults={
            'account_name': "Owner's Equity",
            'account_type': 'Equity',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='3100',
        defaults={
            'account_name': 'Retained Earnings',
            'account_type': 'Equity',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    # Revenue
    Account.objects.get_or_create(
        account_number='4000',
        defaults={
            'account_name': 'Sales Revenue',
            'account_type': 'Revenue',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='4100',
        defaults={
            'account_name': 'Subscription Revenue',
            'account_type': 'Revenue',
            'normal_balance': 'Credit',
            'is_active': True
        }
    )
    
    # Expenses
    Account.objects.get_or_create(
        account_number='5000',
        defaults={
            'account_name': 'Operating Expenses',
            'account_type': 'Expense',
            'normal_balance': 'Debit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='5100',
        defaults={
            'account_name': 'Platform Fee Expense',
            'account_type': 'Expense',
            'normal_balance': 'Debit',
            'is_active': True
        }
    )
    
    Account.objects.get_or_create(
        account_number='5200',
        defaults={
            'account_name': 'Cost of Goods Sold',
            'account_type': 'Expense',
            'normal_balance': 'Debit',
            'is_active': True
        }
    )


def reverse_chart_of_accounts(apps, schema_editor):
    Account = apps.get_model('ledger', 'Account')
    Account.objects.filter(
        account_number__in=[
            '1000', '1100', '1200',  # Assets
            '2000', '2100', '2200',  # Liabilities
            '3000', '3100',  # Equity
            '4000', '4100',  # Revenue
            '5000', '5100', '5200'  # Expenses
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_chart_of_accounts, reverse_chart_of_accounts),
    ]
